# Setup
title:       PghML 
tagline:     Pittsburgh Machine Learning Meetup Group 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       helloimyames
  url:        https://github.com/helloimyames
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
